# Generated by Django 4.0 on 2022-02-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('href', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=20)),
                ('agree', models.CharField(max_length=20, null='yes')),
                ('people', models.CharField(max_length=20, null='yes')),
                ('about', models.CharField(max_length=20, null='yes')),
            ],
        ),
    ]
