# Generated by Django 4.0 on 2022-02-11 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trip',
            new_name='Date',
        ),
    ]
