# Generated by Django 4.0 on 2022-02-11 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_rename_trip_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Date',
            new_name='Data',
        ),
    ]
