# Generated by Django 4.0 on 2022-02-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_rename_date_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=18)),
                ('pass_word', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='User_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('pass_word', models.CharField(max_length=20)),
                ('user_pow', models.CharField(max_length=10)),
            ],
        ),
    ]
